##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.kafka_server:6.0.0 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/etc/confluent/docker/run"
#COPY ./conteco/configs/etc/confluent/docker/healthcheck.sh /etc/confluent/docker/healthcheck.sh
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="kafka_server" \
    CONTECO_NAME="base" \
    CONTECO_TAG="6.0.0" \
    CONTECO_BASE="external.kafka_server:6.0.0" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="kafka_server" \
      io.vcweb.name="base" \
      io.vcweb.tag="6.0.0" \
      io.vcweb.base="external.kafka_server:6.0.0" \
      io.vcweb.build="image-base" \
      io.vcweb.label="kafka_server.base - ContEco" \
      io.vcweb.description="Confluent Server Base image, with configuration changes." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.kafka_server.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
