#!/usr/bin/env bash

export CONTECO_LABEL="kafka-server.base - ContEco"
export CONTECO_DESCRIPTION="Confluent Server Base image, with configuration changes."

export CONTECO_TYPE="kafka-server"
export CONTECO_NAME="base"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="external.kafka-server:5.4.0"
export CONTECO_BUILD="image-base"
