#!/usr/bin/env bash

export CONTECO_LABEL="kafka_server.base - ContEco"
export CONTECO_DESCRIPTION="Confluent Server Base image, with configuration changes."

export CONTECO_TYPE="kafka_server"
export CONTECO_NAME="base"
export CONTECO_TAG="6.0.0"

export CONTECO_BASE="external.kafka_server:6.0.0"
export CONTECO_BUILD="image-base"
