---
version: '3'
services:

# START SERVICE kafka-server.base
  kafka-server:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.kafka-server.base:5.4.0
    environment: ['KAFKA_HEAP_OPTS=-Xmx${CONTECO_DC_KAFKA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY} -Xms${CONTECO_DC_KAFKA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}','KAFKA_BROKER_ID=1','KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181','KAFKA_ADVERTISED_LISTENERS=OVERLAY://kafka:9092${CONTECO_DC_KAFKA_KAFKA_ADVERTISED_LISTENERS}','KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=OVERLAY:PLAINTEXT${CONTECO_DC_KAFKA_KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}','KAFKA_INTER_BROKER_LISTENER_NAME=OVERLAY','KAFKA_AUTO_CREATE_TOPICS_ENABLE=true','KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1','KAFKA_LOG_RETENTION_HOURS=1']
    command: []
    volumes: ['${CONTECO_STACKPREFIX}_kafka_volume:/var/lib/kafka/data']
    ports: [${CONTECO_DC_KAFKA_PORTS}]
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_KAFKA_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_KAFKA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_KAFKA_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_KAFKA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: []
# END SERVICE kafka-server.base

volumes: {${CONTECO_STACKPREFIX}_kafka__volume: { external: true }}
networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
